version: 2
jobs:
  build:
    docker:
       - image: circleci/ruby:2.6.1-node-browsers
       - image: circleci/postgres:9.6.2-alpine
         environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle_ruby_test
          POSTGRES_PASSWORD: ""
    working_directory: ~/calincome

    steps:
      - run:
          name: Install bundler
          command: |
            gem install bundler
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum 'gems.locked' }}
          - v1-dependencies-
      - run:
          name: Override secrets
          command: |
            cp ~/calincome/.circleci/database.yml ~/calincome/config/database.yml
      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle

      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum 'gems.locked' }}

      - run:
          name: Database Setup
          command: |
            RAILS_ENV=test bundle exec rake db:test:prepare

      - run: bundle exec rubocop

      - run:
          name: Deploy if tests pass and branch is master
          command: bundle exec cap production deploy

      # collect reports
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results
