version: "2.1"
orbs:
  node: circleci/node@5.0.0
  ruby: circleci/ruby@1.4.0
executors:
  default:
    docker:
      - image: cimg/ruby:3.1-node
        environment:
          RAILS_ENV: test
      - image: circleci/postgres:13
        environment:
          POSTGRES_USER: calincome
          POSTGRES_DB: calincome_test
          POSTGRES_HOST_AUTH_METHOD: trust

      - image: redis

commands:
  debug:
    steps:
      - run: ruby --version || true
      - run: python --version || true
      - run: python2 --version || true
      - run: python3 --version || true
      - run: node --version || true
      - run: yarn --version || true
      - run: ls -la ~/ -d
  install-yarn:
    steps:
      - node/install-packages:
          pkg-manager: yarn

jobs:
  eslint:
    executor: default
    steps:
      - checkout
      - install-yarn
      - run: yarn run eslint app/javascript

  rubocop:
    executor: default
    steps:
      - checkout
      - ruby/install-deps
      - ruby/rubocop-check

  rspec:
    executor: default
    environment:
      BUNDLE_JOBS: '3'
      BUNDLE_RETRY: '3'
      PGHOST: 127.0.0.1
      PGPASSWORD: ''
      PGUSER: calincome
      RAILS_ENV: test
    parallelism: 3
    steps:
      - checkout
      - install-yarn
      - ruby/install-deps
      - run: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run: bundle exec rails db:schema:load --trace

workflows:
  default:
    jobs:
      - eslint
      - rubocop
      - rspec
