version: 2
jobs:
  build-job:
    docker:
       - image: circleci/ruby:2.6.1-node-browsers
       - image: circleci/postgres:9.6.2-alpine
         environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle_ruby_test
          POSTGRES_PASSWORD: ""
    working_directory: ~/calincome

    steps:
      - run:
          name: Install bundler
          command: |
            gem install bundler
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum 'gems.locked' }}
          - v1-dependencies-
      - run:
          name: Override secrets
          command: |
            cp ~/calincome/.circleci/database.yml ~/calincome/config/database.yml
      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle

      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum 'gems.locked' }}

      - run:
          name: Database Setup
          command: |
            RAILS_ENV=test bundle exec rake db:test:prepare

      - run: bundle exec rubocop

      # collect reports
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results

  deploy-job:
    docker:
       - image: circleci/ruby:2.6.1-node-browsers
    working_directory: ~/calincome
    steps:
      - checkout
      - run:
          name: Override secrets
          command: |
            cp ~/calincome/config/deploy.rb.example ~/calincome/config/deploy.rb
            cp ~/calincome/config/deploy/production.rb.example ~/calincome/config/deploy/production.rb
      - run:
          name: Bundle Install
          command: bundle check || bundle install
      - run:
          name: Deploy to if tests pass and branch is Master
          command: bundle exec cap production deploy

workflows:
  version: 2
  build-deploy:
    jobs:
      - build-job
      - deploy-job:
          requires:
            - build-job
          filters:
            branches:
              only: master
